- name: Deploy Nginx Web Server
  hosts: ec2-instance
  become: yes
  tasks:

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Allow HTTP traffic through UFW
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Deploy Custom Homepage
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
