- name: Perform security updates on EC2 instances
  hosts: patch_targets
  become: yes
  gather_facts: true

  tasks:
    - name: Update package cache
      package:
        update_cache: yes
      when: ansible_pkg_mgr in ['apt', 'yum']

    - name: Apply security updates
      package:
        name: '*'
        state: latest
        update_cache: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Reboot system if necessary
      reboot:
        msg: "System reboot triggered by security updates"
        reboot_timeout: 300
      when: reboot_required.stat.exists or ansible_distribution in ['RedHat', 'CentOS', 'Amazon']

    - name: Verify system uptime
      command: uptime
      register: uptime_output
      changed_when: false

    - name: Display final status
      debug:
        msg: "System updated successfully. Uptime: {{ uptime_output.stdout }}"
