---
- name: Provision AWS EC2 instances and ELB
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        key_name: my-key
        instance_type: t2.micro
        image_id: ami-12345   ### Update with AMI ID
        region: us-east-2
        count: 2
        network:
          vpc_id: "vpc-ID"  ### Update with VPC ID
          subnet_id: "subnet-12345"  ###Update with Subnet ID
          security_group: "sg-123456"  ### Update with Security group
          assign_public_ip: true
        tags:
          Name: WebServer
      register: ec2_instances

    - name: Create ELB
      amazon.aws.elb_classic_lb:
        name: my-load-balancer
        state: present
        region: us-east-2
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
        health_check:
          ping_protocol: http
          ping_port: 80
          ping_path: "/"
          interval: 30
          timeout: 5
          unhealthy_threshold: 2
          healthy_threshold: 2
        subnets:
          - "subnet-12345" ### Update with Subnet ID
      register: elb

    - name: Register instances with ELB
      amazon.aws.elb_classic_lb:
        name: my-load-balancer
        instance_ids: "{{ ec2_instances.instances | map(attribute='instance_id') | list }}"
        state: present
        region: us-east-2
